---
default_language_version:
  python: python3.14

ci:
  skip: [nox-tests]
  autoupdate_schedule: monthly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      # Conflicts with black/ruff formatting
      # - id: double-quote-string-fixer
      - id: no-commit-to-branch
      - id: check-docstring-first
      - id: check-illegal-windows-names
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      # Linter
      - id: ruff-check
      #   args: [ --fix ]
      # Formatter
      - id: ruff-format

  # Ruff already includes isort functionality
  # - repo: https://github.com/asottile/reorder-python-imports
  #   rev: v3.16.0
  #   hooks:
  #     - id: reorder-python-imports
  #       args: [--py312-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - polars==1.35.2

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.1
    hooks:
      - id: pyupgrade
        args: [--py314-plus]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/adamchainz/blacken-docs
    rev: '1.20.0'
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==25.11.0

  - repo: https://github.com/crate-ci/typos
    rev: v1.39.0
    hooks:
      - id: typos

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  # zizmor detects security vulnerabilities in GitHub Actions workflows.
  # Additional configuration for the tool is found in `.github/zizmor.yml`
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.16.3
    hooks:
      - id: zizmor

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt

  # Disabled: ruff
  # - repo: https://github.com/pycqa/flake8
  #   rev: '7.3.0'
  #   hooks:
  #   - id: flake8

  # Disabled for now:
  # * it cannot work with YAML anchors
  # * shellcheck had trouble running
  # mostly copied it from ruff(?) pre-commit config
  # `actionlint` verifies correct syntax in GitHub Actions workflows
  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.7.7
  #   hooks:
  #     - id: actionlint
  #       # stages:
  #       #   - manual  # too slow to run by default?
  #       # args:
  #       #   - "-ignore=SC2129" # ignorable stylistic lint from shellcheck
  #       #   - "-ignore=SC2016" # another shellcheck lint: false positives?
  #       additional_dependencies:
  #         # actionlint has a shellcheck integration which extracts
  #         # shellscripts in `run:` steps from GitHub Actions and checks
  #         # these with shellcheck. This works if shellcheck is installed.
  #         - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0"

  - repo: local
    hooks:
      - id: nox-tests
        name: Quick tests with nox
        entry: nox
        args: ["-t", "pre-commit"]
        language: system
        pass_filenames: false
        types: [python]
        # verbose: true
