---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["pre-commit PR check"]
    types: [completed]
  # pull_request:
  #   branches: ["main"]
  # merge_group:
  #   branches: ["main"]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

# Cancel tests if a new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  test:
    name: tests (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14", "3.13t", "3.14t"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      # - name: setup python, uv and nox
      #   uses: ./.github/actions/setup-python-env
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: install nox
        # uses: wntrblm/nox@0eee2e45758dbd06d48ebb23476439f0f00e5cbd  # 2025.11.12
        # run: uv tool install nox --python ${{ matrix.python-version }}
        run: uv tool install nox
        shell: bash

      - name: run tests
        # run: nox -s tests --force-python ${{ matrix.python-version }}
        run: uvx nox -s tests --force-python ${{ matrix.python-version }}
        shell: bash

  lint:
    name: lint with Ruff (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy: &default-strategy
      matrix:
        python-version: ["3.14"]
        os: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: install nox
        run: uv tool install nox
        shell: bash

      - name: run linting
        run: uvx nox -s lint --force-python ${{ matrix.python-version }}
        shell: bash

  type_check:
    name: type check with mypy (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy: *default-strategy
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: install nox
        run: uv tool install nox
        shell: bash

      - name: Run type check
        run: uvx nox -s type_check --force-python ${{ matrix.python-version }}
        shell: bash

  format:
    name: code formatting check (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy: *default-strategy
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: install nox
        run: uv tool install nox
        shell: bash

      - name: Run format check
        run: uvx nox -s fmt_check --force-python ${{ matrix.python-version }}
        shell: bash

  precommit:
    name: pre-commit checks (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy: *default-strategy
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3  # v7.1.3
        with:
          enable-cache: true

      - name: install pre-commit
        run: uv tool install pre-commit --with pre-commit-uv --python ${{ matrix.python-version }}
        shell: bash

      - name: cache pre-commit cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ github.workflow }}-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}  # yamllint disable-line rule:line-length
      - name: run pre-commit (PR)
        if: github.event_name == 'pull_request'
        run: |
          uvx pre-commit -- run \
            --all-files \
            --show-diff-on-failure \
            --color=always
        shell: bash
        env:
          SKIP: ruff-check,ruff-format,mypy,nox-tests

      - name: run pre-commit (push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          uvx pre-commit -- run \
            --all-files \
            --show-diff-on-failure \
            --color=always
        shell: bash
        env:
          SKIP: ruff-check,ruff-format,mypy,nox-tests,no-commit-to-branch
