name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: ${{ matrix.python-version }}

      - run: nox -s tests --python ${{ matrix.python-version }}

  test_with_coverage:
    name: Test & Coverage (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy: &default-strategy
      matrix:
        python-version: "3.14"
        os: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: ${{ matrix.python-version }}

      - run: nox -s tests_with_coverage --python ${{ matrix.python-version }}

      - run: python ${{ github.workspace }}/.github/extract_coverage.py

      - uses: actions/upload-artifact@v5
        with:
          name: coverage-badge
          path: badges/coverage.json

      - uses: actions/upload-artifact@v5
        with:
          name: coverage-html
          path: htmlcov/

  docs:
    name: Build & Deploy Docs (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    strategy: *default-strategy
    needs: test_with_coverage

    concurrency:
      group: "pages"
      cancel-in-progress: false

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: ${{ matrix.python-version }}

      - run: nox -s docs --python ${{ matrix.python-version }}

      - uses: actions/download-artifact@v6
        with:
          name: coverage-badge
          path: ./docs/_build/html/badges

      - uses: actions/download-artifact@v6
        with:
          name: coverage-html
          path: ./docs/_build/html/htmlcov

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/_build/html

      - id: deployment
        uses: actions/deploy-pages@v4

  lint:
    name: Lint with Ruff (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy: *default-strategy
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: ${{ matrix.python-version }}

      - run: nox -s lint --python ${{ matrix.python-version }}
