name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: "3.14"

      - run: nox -s lint

  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: ${{ matrix.python-version }}

      - run: nox -s tests-${{ matrix.python-version }}

      - if: matrix.python-version == '3.14'
        run: python ${{ github.workspace }}/.github/extract_coverage.py

      - if: matrix.python-version == '3.14'
        uses: actions/upload-artifact@v5
        with:
          name: coverage-badge
          path: badges/coverage.json

      - if: matrix.python-version == '3.14'
        uses: actions/upload-artifact@v5
        with:
          name: coverage-html
          path: htmlcov/


  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test

    concurrency:
      group: "pages"
      cancel-in-progress: false

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v7

      - uses: wntrblm/nox@2025.10.16
        with:
          python-versions: "3.14"

      - run: nox -s docs

      - uses: actions/download-artifact@v6
        with:
          name: coverage-badge
          path: ./docs/_build/html/badges

      - uses: actions/download-artifact@v6
        with:
          name: coverage-html
          path: ./docs/_build/html/htmlcov

      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/_build/html

      - id: deployment
        uses: actions/deploy-pages@v4
