---
name: build documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: build docs, coverage and badge (python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.14"]
        os: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      # - name: setup python, uv and nox
      #   uses: ./.github/actions/setup-python-env
      #   with:
      #     python-version: ${{ matrix.python-version }}

      - name: install uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244  # v7.1.4
        with:
          enable-cache: true

      # - name: install python and nox
      #   uses: wntrblm/nox@0eee2e45758dbd06d48ebb23476439f0f00e5cbd  # 2025.11.12

      # - name: install nox
      #   run: uv tool install nox

      - name: run tests with coverage
        run: uvx nox -s tests_with_coverage --force-python ${{ matrix.python-version }}

      - name: extract coverage badge data
        run: python ${{ github.workspace }}/.github/scripts/extract_coverage.py

      - name: upload coverage badge
        uses: actions/upload-artifact@v6
        with:
          name: coverage-badge
          path: badges/coverage.json
          if-no-files-found: error

      - name: upload coverage HTML report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-html
          path: htmlcov/
          if-no-files-found: error

      - name: build documentation
        run: uvx nox -s docs --force-python ${{ matrix.python-version }}

      - name: upload documnentation HTML
        uses: actions/upload-artifact@v6
        with:
          name: documentation-html
          path: ./docs/_build/html
          if-no-files-found: error

  docs:
    name: deploy docs
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: download documentation HTML artifact
        uses: actions/download-artifact@v7
        with:
          name: documentation-html
          path: ./html

      - name: download coverage badge artifact
        uses: actions/download-artifact@v7
        with:
          name: coverage-badge
          path: ./html/badges

      - name: download coverage HTML report artifact
        uses: actions/download-artifact@v7
        with:
          name: coverage-html
          path: ./html/htmlcov

      - name: make combined artifact available to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./html

      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
